pipeline {
    agent {
        any {
            image 'node:16-alpine'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'node --version'
                sh 'npm install'
                sh 'npm run build'
            }
        }
        stage('Deliver') {
            steps {
                sh 'readlink -f ./package.json'
            }
        }
    }
}
